spring:
  data:
    mongodb:
      username: ${MONGO_ADMIN_USERNAME}
      password: ${MONGO_ADMIN_PASSWORD}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DB}
      authentication-database: admin

server:
    port: ${SERVER_PORT}